version: '3.8'
services:
#  db_first:
#    container_name: ${DB_FIRST_NAME}
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    ports:
#      - "${DB_FIRST_PORT}:5432"
#  node_first:
#    container_name: ${NODE_FIRST_NAME}
#    image: 'certificates-task:0.0.1-SNAPSHOT'
#    depends_on:
#      - db_first
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_FIRST_NAME}:${DB_FIRST_PORT}/${POSTGRES_DB}
#      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
#      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
#      - SERVER_PORT=${NODE_FIRST_PORT}
#      - NODE_NUMBER=1
#      - URLS=[${NODE_SECOND_URL},${NODE_THIRD_URL}]
#      - NODE_NEXTURL=${NODE_SECOND_URL}
#    restart: always
#    ports:
#      - "8080:8080"
  db_second:
    container_name: ${DB_SECOND_NAME}
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DB_SECOND_PORT}:5432"
  node_second:
    container_name: ${NODE_SECOND_NAME}
    image: 'certificates-task:0.0.1-SNAPSHOT'
    depends_on:
      - db_second
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_SECOND_NAME}:${DB_SECOND_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_PORT=${NODE_SECOND_PORT}
      - NODE_NUMBER=2
      - NODE_NEXTURL=${NODE_THIRD_URL}
    restart: always
#  db_third:
#    container_name: ${DB_THIRD_NAME}
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    ports:
#      - "${DB_THIRD_PORT}:5432"
#  node_third:
#    container_name: ${NODE_THIRD_NAME}
#    image: 'certificates-task:0.0.1-SNAPSHOT'
#    depends_on:
#      - db_third
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_THIRD_NAME}:${DB_THIRD_PORT}/${POSTGRES_DB}
#      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
#      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
#      - SERVER_PORT=${NODE_THIRD_PORT}
#      - NODE_NUMBER=3
#    restart: always
