spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: das2632337
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    clean-disabled: false
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  servlet:
    context-path: /api
  port: 8082
node:
  number: 3
  urls:
    - http://localhost:8081
    - http://localhost:8082
  nextNodeUrl: http://localhost:8083
